
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[590] =
    {   0,
        0,    0,    0,    0,    0,    0,   85,   84,   81,   79,
       79,   79,   82,   84,   83,   83,   84,   84,   84,   84,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   82,   82,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   53,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   27,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   29,    0,    0,   10,    0,    0,    0,    0,    0,
        0,    0,   25,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       44,    0,    0,    0,   80,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   43,
        0,   28,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   30,    0,    0,   11,    0,
        0,    0,    0,    0,    0,    0,    0,   26,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   22,    0,   69,    0,   65,   67,   31,
       12,   14,   16,   18,    0,    0,   77,   75,    0,    0,
        0,    0,   63,    0,   61,   33,   73,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   49,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   80,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   80,    0,    0,    0,    0,    0,
       70,    0,   66,   68,   32,   13,   15,   17,   19,    0,
        0,   78,   76,    0,    0,    0,    0,    0,   64,    0,
       62,   34,   74,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   23,    0,
        0,    0,    0,   39,   41,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   24,    0,    0,    0,    0,   40,   42,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    5,    0,    3,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    6,    0,    4,
        2,    0,    0,    0,    0,    0,    0,    0,   72,    0,
        0,    0,    0,    0,   37,    0,    7,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   50,   54,    0,    0,

        0,    0,    0,    0,   38,    0,   60,    8,    0,    0,
        0,    0,   20,   35,    0,    0,    0,   45,    0,    0,
        0,    0,    0,    0,    0,   21,   36,    0,   46,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       52,   56,    0,    9,    0,    0,    0,    0,    0,    0,
        0,   51,   55,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   47,    0,    0,   48,    0,    0,
        0,    0,    0,   57,    0,   58,    0,    0,    0,   71,
        0,    0,    0,    0,    0,    0,    0,   59,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,    1,
        1,    1,    1,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   12,   12,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   32,   32,   36,   37,   38,   39,   40,
       32,   41,   42,   43,   44,   45,   32,   46,   47,   32,
       48,   49,   48,   50,   51,   48,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   32,   32,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   76,    1,   77,   78,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    2,    3,    4,    1,    5,    6,    1,    1,    1,
        7,    2,    1,    8,    7,    4,    4,    4,    4,    4,
        4,    7,    2,    1,    7,    6,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,   10,   10,
       10,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    1,    1,    1
    } ;

static const flex_int16_t yy_base[601] =
    {   0,
        0,   78,    8,    9,    0,    1,  881,  882,  882,  882,
      839,  130,   15,  199,  882,  866,  852,  821,  809,  815,
      815,  812,  816,  815,  805,  817,  804,  815,    2,  806,
        4,  805,  803,  807,  806,  796,  808,  795,  806,  795,
        5,  797,  795,   15,  794,    0,   25,    1,  242,    4,
      822,    3,  815,   75,  825,  815,  813,  822,   10,   66,
        6,  843,   44,  790,  785,  782,   11,   80,   63,  783,
      781,  815,   43,   64,   29,  814,  882,  779,  784,  782,
      772,  770,  765,  772,  764,  769,  761,  767,  768,  804,
      768,  755,  768,  800,  757,  752,  759,  751,  756,  748,

      754,  759,  754,  790,  748,  753,  740,  753,  785,  794,
      767,   18,  774,   87,  767,  121,  777,  767,  765,  774,
       77,  107,  109,   89,  743,  738,  735,   83,  188,  770,
      735,  733,  767,  105,  157,  118,  882,  762,  765,  752,
      763,  743,  761,  760,  759,  758,  757,  756,  755,  753,
      742,  882,  752,  751,  882,  749,  734,   12,  748,  730,
      746,  745,  882,  744,  118,  714,  742,  704,  695,  739,
      706,  700,  736,  735,  734,  733,  706,  695,  698,  729,
      728,  701,  685,  106,  698,  724,  680,  722,  721,  720,
      882,  687,  719,  674,  882,  683,  689,  671,  679,  676,

      685,  683,  712,  672,  710,  663,  672,  678,  660,  668,
      665,  674,  672,  666,  700,  699,  659,  697,  650,  882,
      689,  882,  687,  678,  689,  669,  687,  686,  685,  684,
      683,  682,  681,  679,  668,  882,  678,  677,  882,  675,
      660,  140,  672,  673,  655,  671,  670,  882,  669,  639,
      630,  621,  665,  632,  626,  662,  661,  660,  659,  632,
      621,  656,  655,  628,  612,  131,  625,  651,  607,  649,
      648,  647,  625,  882,  628,  882,  644,  882,  882,  882,
      882,  882,  882,  882,  639,  632,  882,  882,  631,  627,
      639,  638,  882,  627,  882,  882,  882,  595,  609,  586,

      590,  632,   92,  588,  601,  594,  882,  593,  589,  626,
      625,  589,  588,  589,   14,  588,  594,  622,  592,  582,
      590,  618,  585,  587,  882,  586,  585,  613,  583,  573,
      581,  609,  576,  578,  882,  577,  576,  584,  579,  582,
      882,  598,  882,  882,  882,  882,  882,  882,  882,  593,
      586,  882,  882,  585,  581,  593,  592,  581,  882,  580,
      882,  882,  882,  541,  545,  587,  146,  543,  556,  549,
      548,  544,  581,  580,  544,  543,  577,  571,  882,  575,
      574,  563,  560,  882,  882,  566,  540,  533,  568,  537,
      539,  523,  585,  562,  553,  514,  511,  517,  499,  485,

        0,    0,  522,  523,  488,  446,  486,  456,  484,  483,
      482,  480,  438,  478,  448,  475,  474,  473,  448,  468,
      462,  882,  466,  465,  454,  451,  882,  882,  457,  456,
      460,  429,  432,  416,  456,  452,  451,  415,  410,  415,
      412,  882,  425,  882,  882,  439,  429,  435,  403,  402,
      390,  390,  398,  385,  426,  390,  431,  404,  403,  420,
      414,   30,  361,  399,  358,  394,  376,  882,  373,  882,
      882,  387,  379,  384,  375,  331,  332,  339,  882,  367,
      330,  361,  360,  359,  882,  357,  882,  357,  348,  345,
      301,  337,  295,  327,  299,  181,  882,  882,  202,  229,

      328,  327,  318,  311,  882,  310,  882,  882,  301,  257,
      299,  298,  882,  882,  268,    0,  262,  882,  246,  245,
      271,  297,  313,  324,  282,  882,  882,  245,  882,  313,
      339,  289,    0,  341,  274,  216,  223,  207,  341,  358,
      882,  882,  240,  239,  198,  237,  365,  216,  174,  211,
      177,  882,  882,  168,  210,  374,  200,  187,  200,  154,
      176,  149,  377,  141,  882,  388,  122,  882,  152,  408,
      143,  425,  126,  882,  412,  882,  106,   99,  424,  882,
       18,  444,   92,   55,  449,   32,   11,  882,  882,  512,
      522,  532,  541,  549,  551,  554,  561,  567,  576,  583

    } ;

static const flex_int16_t yy_def[601] =
    {   0,
      590,  590,  591,  591,  592,  592,  589,  589,  589,  589,
      589,  589,  593,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  594,  593,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,

      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,

      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,

      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,

      595,  596,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  595,
      596,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,

      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  597,  598,  589,  589,  589,  589,
      589,  589,  589,  589,  599,  589,  589,  589,  589,  597,
      597,  589,  600,  597,  598,  589,  589,  589,  589,  589,
      589,  589,  599,  599,  589,  600,  597,  589,  589,  589,
      589,  589,  589,  589,  589,  597,  589,  589,  589,  589,
      589,  589,  597,  589,  589,  589,  589,  589,  589,  597,
      589,  589,  589,  589,  597,  589,  589,  589,  597,  589,
      589,  597,  589,  589,  597,  589,  589,  589,    0,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589

    } ;

static const flex_int16_t yy_nxt[961] =
    {   0,
        8,    8,    9,    8,    8,    8,   10,   11,   10,   12,
        8,    8,    8,  110,   17,   17,   46,   46,   46,  401,
       16,   16,  589,   14,  402,    8,   46,   46,   46,  137,
      111,  163,  141,  583,  584,  499,  588,  142,  143,  291,
      500,  164,  138,  222,  139,  144,  156,    8,   10,   10,
       10,  292,  157,  158,  163,   92,  223,  588,   18,   18,
       89,   90,   93,  103,  104,  587,  107,   19,   19,  137,
      171,   20,   20,  108,  172,   10,   10,   10,    8,    8,
        9,    8,    8,    8,   10,   11,   10,   12,  152,  190,
        8,  146,  147,  148,  149,  159,  173,  174,  175,  176,

      160,   14,  586,    8,  182,  150,  161,  166,  162,  581,
      167,  183,  184,  240,  222,  185,  225,  151,  186,  241,
      242,  226,  227,  187,  179,    8,   10,   10,   10,  228,
      188,  580,  189,  243,  248,  177,  244,  230,  231,  232,
      233,  245,  254,  248,  249,  391,  255,  246,  178,  247,
      578,  234,  250,   10,   10,   10,   22,   23,  310,   24,
       25,  392,   26,  235,   27,   28,  264,  356,  576,   29,
      311,   30,   31,  265,  266,   32,  298,  574,  272,  357,
      299,   33,   34,  373,   35,   36,  521,   37,  573,   38,
       39,  522,  571,   40,   41,  374,   42,   43,   44,  433,

      569,  568,   45,   48,  256,  257,  258,  259,  267,  567,
      566,  268,  565,   49,  564,  434,  269,  523,  523,  523,
      523,  523,  523,  270,  562,  271,   50,   51,   52,   53,
      561,  560,   54,   55,   56,  559,  558,   57,   58,  557,
       59,   60,   61,  260,  524,  524,  524,  524,  524,  524,
       62,   63,   64,   65,   66,   67,  261,   68,   69,   70,
      555,  554,   71,   72,  544,  544,   73,   74,   75,  112,
      113,  114,  115,  551,  531,  116,  117,  118,  550,  549,
      119,  120,  532,  121,  122,  123,  539,  539,  539,  539,
      539,  539,  531,  533,  124,  125,  126,  127,  128,  548,

      129,  130,  131,  531,  545,  132,  133,  544,  538,  134,
      135,  136,  540,  540,  540,  540,  540,  540,  541,  531,
      537,  536,  534,  527,  529,  528,  526,  532,  523,  523,
      523,  523,  523,  523,  542,  527,  526,  531,  533,  524,
      524,  524,  524,  524,  524,  531,  552,  531,  525,  335,
      325,  520,  514,  532,  519,  532,  539,  539,  539,  539,
      539,  539,  518,  531,  533,  531,  533,  534,  553,  517,
      513,  531,  516,  540,  540,  540,  540,  540,  540,  532,
      531,  515,  514,  531,  513,  508,  507,  512,  532,  531,
      533,  532,  505,  534,  511,  534,  510,  509,  531,  533,

      508,  531,  533,  572,  572,  572,  572,  572,  572,  507,
      547,  506,  505,  504,  531,  503,  195,  556,  531,  534,
      502,  195,  532,  501,  498,  497,  532,  496,  534,  487,
      531,  534,  531,  533,  495,  577,  531,  533,  532,  563,
      572,  572,  572,  572,  572,  572,  570,  494,  531,  533,
      531,  485,  493,  492,  491,  531,  490,  489,  532,  488,
      487,  486,  534,  532,  485,  484,  534,  483,  531,  533,
      482,  575,  481,  531,  533,  480,  471,  470,  534,  582,
      579,  479,  478,  477,  476,  468,  475,  474,  473,  472,
      471,  470,  469,  468,  467,  335,  195,  195,  534,  466,

      335,  465,  335,  534,  335,  335,  195,  464,  335,  463,
      335,  585,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,   47,   47,   47,  325,  462,   47,   47,   47,
       46,   46,   46,  459,  458,   46,   46,   46,  460,  460,
      460,  461,  461,  461,  530,  530,  530,  530,  530,  530,
      535,  535,  457,  456,  455,  535,  543,  543,  445,  543,
      543,  543,  543,  543,  543,  543,  546,  444,  454,  453,
      452,  546,  451,  442,  450,  449,  448,  447,  446,  445,

      444,  443,  442,  441,  440,  428,  427,  439,  438,  437,
      436,  435,  422,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  335,  414,  413,  412,  335,  411,  410,  409,  408,
      325,  407,  406,  405,  325,  404,  403,  400,  399,  398,
      385,  384,  397,  396,  395,  394,  393,  379,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  377,  363,  362,  361,  376,  359,  375,  372,  371,
      353,  352,  370,  369,  349,  348,  347,  346,  368,  367,
      345,  366,  365,  364,  363,  362,  361,  360,  359,  358,

      355,  354,  353,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  195,
      336,  335,  195,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  195,  323,  322,  321,  320,  319,
      318,  317,  316,  315,  314,  297,  296,  295,  313,  293,
      312,  309,  308,  288,  287,  307,  306,  305,  284,  283,
      282,  281,  304,  303,  280,  302,  301,  274,  300,  297,
      296,  295,  294,  293,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  239,  263,  262,  236,  253,  252,  251,  239,

      238,  237,  236,  229,  224,  221,  220,  195,  219,  218,
      217,  216,  195,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  195,  206,  205,  204,  195,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      155,  181,  180,  170,  169,  168,  165,  155,  154,  153,
      152,  145,  140,  109,  106,  105,  102,  101,  100,   99,
       98,   97,   96,   95,   94,   91,   88,   87,   86,   85,
       84,   83,   82,   81,   80,   79,   78,   77,   76,   21,
      589,    7,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,

      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589
    } ;

static const flex_int16_t yy_chk[961] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    1,   48,    5,    6,   13,   13,   13,  315,
        3,    4,    0,    1,  315,    1,   47,   47,   47,   50,
       48,   61,   52,  581,  581,  462,  587,   52,   52,  158,
      462,   61,   50,  112,   50,   52,   59,    1,    1,    1,
        1,  158,   59,   59,   75,   31,  112,  586,    5,    6,
       29,   29,   31,   41,   41,  584,   44,    5,    6,   63,
       67,    5,    6,   44,   67,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,   69,   75,
        2,   54,   54,   54,   54,   60,   68,   68,   68,   68,

       60,    2,  583,    2,   73,   54,   60,   63,   60,  578,
       63,   73,   73,  121,  124,   74,  114,   54,   74,  121,
      121,  114,  114,   74,   69,    2,    2,    2,    2,  114,
       74,  577,   74,  122,  123,   68,  122,  116,  116,  116,
      116,  122,  128,  136,  123,  303,  128,  122,   68,  122,
      573,  116,  124,    2,    2,    2,   12,   12,  184,   12,
       12,  303,   12,  116,   12,   12,  134,  242,  571,   12,
      184,   12,   12,  134,  134,   12,  165,  569,  136,  242,
      165,   12,   12,  266,   12,   12,  496,   12,  567,   12,
       12,  496,  564,   12,   12,  266,   12,   12,   12,  367,

      562,  561,   12,   14,  129,  129,  129,  129,  135,  560,
      559,  135,  558,   14,  557,  367,  135,  499,  499,  499,
      499,  499,  499,  135,  555,  135,   14,   14,   14,   14,
      554,  551,   14,   14,   14,  550,  549,   14,   14,  548,
       14,   14,   14,  129,  500,  500,  500,  500,  500,  500,
       14,   14,   14,   14,   14,   14,  129,   14,   14,   14,
      546,  545,   14,   14,  544,  543,   14,   14,   14,   49,
       49,   49,   49,  538,  515,   49,   49,   49,  537,  536,
       49,   49,  515,   49,   49,   49,  521,  521,  521,  521,
      521,  521,  515,  515,   49,   49,   49,   49,   49,  535,

       49,   49,   49,  532,  528,   49,   49,  525,  520,   49,
       49,   49,  522,  522,  522,  522,  522,  522,  523,  530,
      519,  517,  515,  512,  511,  510,  509,  530,  523,  523,
      523,  523,  523,  523,  524,  506,  504,  530,  530,  524,
      524,  524,  524,  524,  524,  531,  539,  534,  503,  502,
      501,  495,  494,  531,  493,  534,  539,  539,  539,  539,
      539,  539,  492,  531,  531,  534,  534,  530,  540,  491,
      490,  547,  489,  540,  540,  540,  540,  540,  540,  547,
      556,  488,  486,  563,  484,  483,  482,  481,  556,  547,
      547,  563,  480,  531,  478,  534,  477,  476,  556,  556,

      475,  563,  563,  566,  566,  566,  566,  566,  566,  474,
      534,  473,  472,  469,  570,  467,  466,  547,  575,  547,
      465,  464,  570,  463,  461,  460,  575,  459,  556,  458,
      579,  563,  570,  570,  457,  572,  575,  575,  579,  556,
      572,  572,  572,  572,  572,  572,  563,  456,  579,  579,
      582,  455,  454,  453,  452,  585,  451,  450,  582,  449,
      448,  447,  570,  585,  446,  443,  575,  441,  582,  582,
      440,  570,  439,  585,  585,  438,  437,  436,  579,  579,
      575,  435,  434,  433,  432,  431,  430,  429,  426,  425,
      424,  423,  421,  420,  419,  418,  417,  416,  582,  415,

      414,  413,  412,  585,  411,  410,  409,  408,  407,  406,
      405,  582,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  591,  591,  591,  591,  591,  591,  591,  591,
      591,  591,  592,  592,  592,  592,  592,  592,  592,  592,
      592,  592,  593,  593,  593,  404,  403,  593,  593,  593,
      594,  594,  594,  400,  399,  594,  594,  594,  595,  595,
      595,  596,  596,  596,  597,  597,  597,  597,  597,  597,
      598,  598,  398,  397,  396,  598,  599,  599,  395,  599,
      599,  599,  599,  599,  599,  599,  600,  394,  393,  392,
      391,  600,  390,  389,  388,  387,  386,  383,  382,  381,

      380,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  366,  365,  364,  360,  358,  357,  356,  355,
      354,  351,  350,  342,  340,  339,  338,  337,  336,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  314,  313,  312,
      311,  310,  309,  308,  306,  305,  304,  302,  301,  300,
      299,  298,  294,  292,  291,  290,  289,  286,  285,  277,
      275,  273,  272,  271,  270,  269,  268,  267,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  247,  246,  245,  244,  243,

      241,  240,  238,  237,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  221,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  194,  193,  192,  190,  189,  188,  187,  186,
      185,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  164,
      162,  161,  160,  159,  157,  156,  154,  153,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  133,  132,  131,  130,  127,  126,  125,  120,

      119,  118,  117,  115,  113,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,
       96,   95,   94,   93,   92,   91,   90,   89,   88,   87,
       86,   85,   84,   83,   82,   81,   80,   79,   78,   76,
       72,   71,   70,   66,   65,   64,   62,   58,   57,   56,
       55,   53,   51,   45,   43,   42,   40,   39,   38,   37,
       36,   35,   34,   33,   32,   30,   28,   27,   26,   25,
       24,   23,   22,   21,   20,   19,   18,   17,   16,   11,
        7,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,

      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589,
      589,  589,  589,  589,  589,  589,  589,  589,  589,  589
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "P7.l"
/*
$ bison -d P7.y
$ flex P7.l
$ $ gcc -o P7 P7.tab.c lex.yy.c P7.c
*/

#line 9 "P7.l"
#include <stdio.h>
# include "P7.h"
# include "P7.tab.h"
	extern char border;
#line 860 "lex.yy.c"

#line 862 "lex.yy.c"

#define INITIAL 0
#define COMM 1
#define IMG_ARG 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 33 "P7.l"


#line 1084 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 590 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 882 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "P7.l"
{ 	return HTML_STRT;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "P7.l"
{	return HTML_END;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "P7.l"
{ 
							yylval.p=(char *)malloc(100);
							strcpy(yylval.p,"\\documentclass{article}");
							strcat(yylval.p,"\\usepackage{hyperref}");
							strcat(yylval.p,"\\usepackage{graphicx}");
							strcat(yylval.p,"\\begin{document}");
							return HEAD_STRT;
						}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "P7.l"
{ 	return HEAD_END;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "P7.l"
{ 	return BODY_STRT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "P7.l"
{  
							yylval.p=(char *)malloc(100);
							strcpy(yylval.p,"\\end{document}");
							return BODY_END;			
						}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "P7.l"
{
							yylval.p=(char *)malloc(100);
							strcpy(yylval.p,"\\title{");
							return TITLE_STRT;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "P7.l"
{
							yylval.p=(char *)malloc(100);
							strcpy(yylval.p,"}\\maketitle ");
							return TITLE_END;
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 70 "P7.l"
;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "P7.l"
{	 
							yylval.p=(char *)malloc(8);
							strcpy(yylval.p,"\\par ");
							return P_STRT;
						}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 77 "P7.l"
{	return P_END;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 79 "P7.l"
{	 
							yylval.p=(char *)malloc(10);
							strcpy(yylval.p,"\\section{");
							return H1_STRT;
						}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 84 "P7.l"
{	return H1_END;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "P7.l"
{	
							yylval.p=(char *)malloc(13);
							strcpy(yylval.p,"\\subsection{");
							return H2_STRT;
						}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 "P7.l"
{ return H2_END;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 "P7.l"
{
							yylval.p=(char *)malloc(16);
							strcpy(yylval.p,"\\subsubsection{");	
							return H3_STRT;
						}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "P7.l"
{	return H3_END;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 99 "P7.l"
{	
							yylval.p=(char *)malloc(16);
							strcpy(yylval.p,"\\subsubsection{");
							return H4_STRT;
						}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "P7.l"
{	return H4_END;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "P7.l"
{	
							yylval.p=(char *)malloc(15);
							strcpy(yylval.p,"\\begin{center}");
							return CENTER_STRT;
						}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 111 "P7.l"
{	return CENTER_END;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 113 "P7.l"
{	return BR_STRT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 115 "P7.l"
{	return DIV_STRT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "P7.l"
{	return DIV_END;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 118 "P7.l"
{ 
							yylval.p = (char *)malloc(12);
							strcpy(yylval.p,"\\underline{");
							return U_STRT;
						}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 123 "P7.l"
{ 	return U_END;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 125 "P7.l"
{ 
							yylval.p = (char *)malloc(9);
							strcpy(yylval.p,"\\textbf{");
							return B_STRT;
						}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 130 "P7.l"
{ 	return B_END;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "P7.l"
{ 
							yylval.p = (char *)malloc(8);
							strcpy(yylval.p,"\\textit{");
							return I_STRT;
						}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 137 "P7.l"
{ 	return I_END;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 139 "P7.l"
{	
							yylval.p = (char *)malloc(7);
							strcpy(yylval.p,"\\emph{");
							return EM_STRT;
						}	
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 144 "P7.l"
{	return EM_END;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "P7.l"
{	
							yylval.p = (char *)malloc(9);
							strcpy(yylval.p,"\\texttt{");
							return TT_STRT;
						}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 151 "P7.l"
{	return TT_END;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 153 "P7.l"
{	
							yylval.p = (char *)malloc(9);
							strcpy(yylval.p,"\\textbf{");
							return STRONG_STRT;
						}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 158 "P7.l"
{	return STRONG_END;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 160 "P7.l"
{	
							yylval.p = (char *)malloc(8);
							strcpy(yylval.p,"\\small{");
							return SMALL_STRT;
						}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 165 "P7.l"
{	return SMALL_END;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 167 "P7.l"
{	
							yylval.p = (char *)malloc(3);
							strcpy(yylval.p,"$_{");
							return SUB_STRT;
						}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 172 "P7.l"
{	return SUB_END;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 174 "P7.l"
{	
							yylval.p = (char *)malloc(3);
							strcpy(yylval.p,"$^{");
							return SUP_STRT;
						}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 179 "P7.l"
{	return SUP_END;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 182 "P7.l"
{	BEGIN(COMM);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 183 "P7.l"
{	BEGIN(INITIAL);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 185 "P7.l"
{
							yylval.p = (char *)malloc(20);
							strcpy(yylval.p,"\\begin{figure}");	
							 return FIG_STRT;
						}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 191 "P7.l"
{
							 return FIG_END;
						}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 195 "P7.l"
{
							return FIGC_STRT;
						}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 198 "P7.l"
{
							return FIGC_END;
						}						
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 204 "P7.l"
{ printf("img detected"); BEGIN(IMG_ARG);return IMG_STRT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 205 "P7.l"
{ printf("src detected"); 
                                        char * s=(char *)malloc(100);
                                       strcpy(s,yytext);

                                       char * k=(char *)malloc(100);

                                       int i=0;int j=0;
                                       while(s[i]!='"'){i++;}i++;

                                       while(s[i]!='"'){k[j]=s[i];j++;i++;}k[j]='\0';
                                       yylval.p=(char *)malloc(100);
                                       strcpy(yylval.p,k); printf("%s",k);
                                       return IMG_SRC;
                                         }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 220 "P7.l"
{ printf("height detected %s",yytext);
                                       char * s=(char *)malloc(100);
                                       strcpy(s,yytext);

                                       char * k=(char *)malloc(100);

                                       int i=0;int j=0;
                                       while(s[i]!='"'){i++;}i++;

                                       while(s[i]!='"'){k[j]=s[i];j++;i++;}k[j]='\0';
                                       yylval.p=(char *)malloc(100);
                                       strcpy(yylval.p,k); printf("%s",k);
                                       	return IMG_HT;
                                       }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 235 "P7.l"
{ printf("width detected %s",yytext);
                                       char * s=(char *)malloc(100);
                                       strcpy(s,yytext);

                                       char * k=(char *)malloc(100);

                                       int i=0;int j=0;
                                       while(s[i]!='"'){i++;}i++;

                                       while(s[i]!='"'){k[j]=s[i];j++;i++;}k[j]='\0';
                                       yylval.p=(char *)malloc(100);
                                       strcpy(yylval.p,k); printf("%s",k);
                                       return IMG_WT;
                                  }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 250 "P7.l"
{ printf("img end detected"); BEGIN 0; return IMG_END;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 253 "P7.l"
{ printf("src detected"); 
                                        char * s=(char *)malloc(100);
                                       strcpy(s,yytext);

                                       char * k=(char *)malloc(100);

                                       int i=0;int j=0;
                                       while(s[i]!='\''){i++;}i++;

                                       while(s[i]!='\''){k[j]=s[i];j++;i++;}k[j]='\0';
                                       yylval.p=(char *)malloc(100);
                                       strcpy(yylval.p,k); printf("%s",k);
                                       return IMG_SRC;
                                         }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 268 "P7.l"
{ printf("height detected %s",yytext);
                                       char * s=(char *)malloc(100);
                                       strcpy(s,yytext);

                                       char * k=(char *)malloc(100);

                                       int i=0;int j=0;
                                       while(s[i]!='\''){i++;}i++;

                                       while(s[i]!='\''){k[j]=s[i];j++;i++;}k[j]='\0';
                                       yylval.p=(char *)malloc(100);
                                       strcpy(yylval.p,k); printf("%s",k);
                                       	return IMG_HT;
                                       }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 283 "P7.l"
{ printf("width detected %s",yytext);
                                       char * s=(char *)malloc(100);
                                       strcpy(s,yytext);

                                       char * k=(char *)malloc(100);

                                       int i=0;int j=0;
                                       while(s[i]!='\''){i++;}i++;

                                       while(s[i]!='\''){k[j]=s[i];j++;i++;}k[j]='\0';
                                       yylval.p=(char *)malloc(100);
                                       strcpy(yylval.p,k); printf("%s",k);
                                       return IMG_WT;
                                  }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 300 "P7.l"
{	

							char *ch1, *ch2;int i,j;
							yylval.p = (char *)malloc(100);
							ch1 = (char *)malloc(50);
							ch2 = (char *)malloc(50);
							for(i=9;yytext[i]!='\"';i++)
								ch1[i-9]=yytext[i];
							strcat(yylval.p,"\\href{");
							strcat(yylval.p,ch1);
							strcat(yylval.p,"}");
							while(yytext[i]!='>')
								i++;

							j=i+1;
							for(i;yytext[i]!='<';i++)
								ch2[i-j]=yytext[i];
							strcat(yylval.p,"{");
							strcat(yylval.p,ch2);
							strcat(yylval.p,"}");
							return A_STRT;
						}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 323 "P7.l"
{
						
							int i;
							yylval.p = (char *)malloc(100);
							char *ch = (char *)malloc(50);
							for(i=9;yytext[i]!='\"';i++)
								ch[i-9]=yytext[i];

							strcat(yylval.p,"\\label{");
							strcat(yylval.p,ch);
							strcat(yylval.p,"}");
							return NAME_STRT;
						}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 337 "P7.l"
{ 


						if(yytext[15]=='1')
							border='1';
						else
							border='0';

							yylval.p=(char *)malloc(40);
							//strcpy(yylval.p,"\\begin{tabular}");
							strcpy(yylval.p,yytext);
							return TAB_STRT;
						}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 350 "P7.l"
{	return TAB_END;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 351 "P7.l"
{	return ROW_STRT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 352 "P7.l"
{	return ROW_END;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 353 "P7.l"
{ 	return COL_STRT;} 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 354 "P7.l"
{   return COL_END;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 356 "P7.l"
{ 	return DL_STRT;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 357 "P7.l"
{ 	return DL_END;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 358 "P7.l"
{ 	return DT_STRT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 359 "P7.l"
{ 	return DT_END;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 360 "P7.l"
{ 	return DD_STRT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 361 "P7.l"
{ 	return DD_END;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 363 "P7.l"
{
							yylval.p = (char *)malloc(yyleng);
							strcpy(yylval.p,yytext);
							return FONT_STRT;
						}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 369 "P7.l"
{	return FONT_END;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 370 "P7.l"
{	
							yylval.p=(char *)malloc(16);
							strcpy(yylval.p,"\\begin{itemize}");
							return UL_STRT;
						}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 375 "P7.l"
{	
							yylval.p=(char *)malloc(14);
							strcpy(yylval.p,"\\end{itemize}");
							return UL_END;
						}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 381 "P7.l"
{	
							yylval.p=(char *)malloc(18);
							strcpy(yylval.p,"\\begin{enumerate}");
							return OL_STRT;
						}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 386 "P7.l"
{	
							yylval.p=(char *)malloc(16);
							strcpy(yylval.p,"\\end{enumerate}");
							return OL_END;
						}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 392 "P7.l"
{	
							yylval.p=(char *)malloc(7);
							strcpy(yylval.p,"\\item ");
							return LI_STRT;
						}	
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 397 "P7.l"
{	return LI_END;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 399 "P7.l"
{
							yylval.p=(char *)malloc(yyleng+5);
							if(yytext[0]=='\\' && yyleng==1)
								strcpy(yylval.p,"$\\backslash$ ");
							else
							{
							strcpy(yylval.p,"\\");
							strcat(yylval.p,yytext);
							strcat(yylval.p," ");
							} 
							return SPECIAL;
						}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 411 "P7.l"
{
							yylval.p=(char *)malloc(yyleng);	
							char *ch = (char *)malloc(yyleng-2); 
							int i;
							if(yytext[1]=='A')
								strcpy(yylval.p,"A ");
							else if (yytext[1]=='B')
								strcpy(yylval.p,"B ");
							else if (yytext[1]=='E')
								strcpy(yylval.p,"E ");
							else if (yytext[1]=='I')
								strcpy(yylval.p,"E ");
							else if (yytext[1]=='T')
								strcpy(yylval.p,"T ");
							else if (yytext[1]=='R')
								strcpy(yylval.p,"P ");
							else
							{
							for(i=1;i<yyleng-1;i++)
								ch[i-1]=yytext[i];
							strcpy(yylval.p,"$\\");
							strcat(yylval.p,ch);
							strcat(yylval.p,"$ ");
							}
							return GSYMBOLS; 
						}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 437 "P7.l"
;
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 438 "P7.l"
{ 
							yylval.p=(char *)malloc(yyleng);
							strcpy(yylval.p,yytext);
						 	return TEXT;
		 				};
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 444 "P7.l"
;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 446 "P7.l"
ECHO;
	YY_BREAK
#line 1839 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMM):
case YY_STATE_EOF(IMG_ARG):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 590 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 590 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 589);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 446 "P7.l"

